package com.bandarovich.pharmacy.command;

public enum CommandType {
    SET_LOCALE,
    REGISTRATION,
    LOG_IN,
    LOG_OUT,
    BOOK_MEDICINE,
    COMPLETE_ORDER,
    CLIENT_MEDICINE_LIST,
    CLIENT_PRESCRIPTION_LIST,
    REQUEST_PRESCRIPTION_FOR_EXTENSION,
    ALL_CLIENT_MEDICINE_LIST,
    DOCTOR_MEDICINE_LIST,
    DOCTOR_PRESCRIPTION_LIST,
    WRITE_PRESCRIPTION,
    START_PAGE
}
