package com.bandarovich.pharmacy.command;

public enum CommandType {
    REGISTRATION,
    LOG_IN,
    LOG_OUT,
    BOOK_MEDICINE,
    COMPLETE_ORDER,
    CLIENT_MEDICINE_LIST,
    CLIENT_PRESCRIPTION_LIST,
    ALL_CLIENT_MEDICINE_LIST,
    TRY_ORDER_MEDICINE,
    ADD_ORDER_MEDICINE,
    DOCTOR_MEDICINE_LIST,
    DOCTOR_PRESCRIPTION_LIST,
    WRITE_PRESCRIPTION,
    START_PAGE
}
